kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: message-system
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 3000
    protocol: TCP
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP 