apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
  namespace: message-system
spec:
  template:
    spec:
      containers:
        - name: init
          image: conicle/dso-exam-01-backend:v1.0.1
          args:
            - "./main"
            - "init"
            - "--brokers=kafka:9092"
            - "--topics=messages,notify-messages"
            - "--partitions=3"
            - "--replication-factor=1"
            - "--init-db"
            - "--db-conn=postgres://postgres:postgres@postgres:5432/messages?sslmode=disable"
          env:
            - name: APP_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
      restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: message-system
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: message-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: conicle/dso-exam-01-backend:v1.0.1
          args:
            - "./main"
            - "serve"
            - "--addr=0.0.0.0"
            - "--port=8080"
            - "--cors-allowed-origins=*"
            - "--brokers=kafka:9092"
            - "--group-id=notify-consumer"
            - "--message-topic=messages"
            - "--notify-topic=notify-messages"
            - "--db-conn=postgres://postgres:postgres@postgres:5432/messages?sslmode=disable"
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "json"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: message-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: conicle/dso-exam-01-backend:v1.0.1
          args:
            - "./main"
            - "consume"
            - "--brokers=kafka:9092"
            - "--message-topic=messages"
            - "--notify-topic=notify-messages"
            - "--group-id=messages-consumer"
            - "--db-conn=postgres://postgres:postgres@postgres:5432/messages?sslmode=disable"
          env:
            - name: APP_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "json" 