kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: event-driven-message-system
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  - containerPort: 30090
    hostPort: 3000
    protocol: TCP
  extraMounts:
  - hostPath: /tmp/strimzi-data
    containerPath: /var/lib/strimzi
